# Generated by Django 2.2.6 on 2019-11-10 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('gene_symbol', models.CharField(max_length=100)),
                ('control1', models.DecimalField(decimal_places=5, max_digits=8)),
                ('control2', models.DecimalField(decimal_places=5, max_digits=8)),
                ('control3', models.DecimalField(decimal_places=5, max_digits=8)),
                ('control4', models.DecimalField(decimal_places=5, max_digits=8)),
                ('control5', models.DecimalField(decimal_places=5, max_digits=8)),
                ('kras1', models.DecimalField(decimal_places=5, max_digits=8)),
                ('kras2', models.DecimalField(decimal_places=5, max_digits=8)),
                ('kras3', models.DecimalField(decimal_places=5, max_digits=8)),
                ('kras4', models.DecimalField(decimal_places=5, max_digits=8)),
                ('kras5', models.DecimalField(decimal_places=5, max_digits=8)),
            ],
        ),
    ]
