# Generated by Django 2.2.6 on 2020-01-10 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0003_auto_20200102_1204'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllPro',
            fields=[
                ('protein_id', models.TextField(blank=True, db_column='Protein Id', null=True)),
                ('id', models.TextField(blank=True, db_column='Id', primary_key=True, serialize=False)),
                ('gene_symbol', models.TextField(blank=True, db_column='Gene Symbol', null=True)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
            ],
            options={
                'db_table': 'all_pro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ColonTumorPro',
            fields=[
                ('protein_id', models.TextField(blank=True, db_column='Protein Id', null=True)),
                ('gene_symbol', models.TextField(blank=True, db_column='Gene Symbol', null=True)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
                ('number_of_peptides', models.TextField(blank=True, db_column='Number of peptides', null=True)),
                ('control1', models.TextField(blank=True, null=True)),
                ('control2', models.TextField(blank=True, null=True)),
                ('control3', models.TextField(blank=True, null=True)),
                ('control4', models.TextField(blank=True, null=True)),
                ('control5', models.TextField(blank=True, null=True)),
                ('kras1', models.TextField(blank=True, db_column='KRAS1', null=True)),
                ('kras2', models.TextField(blank=True, db_column='KRAS2', null=True)),
                ('kras3', models.TextField(blank=True, db_column='KRAS3', null=True)),
                ('kras4', models.TextField(blank=True, db_column='KRAS4', null=True)),
                ('kras5', models.TextField(blank=True, db_column='KRAS5', null=True)),
                ('id', models.TextField(blank=True, db_column='Id', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'colon_tumor_pro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PancreasTumorPro',
            fields=[
                ('protein_id', models.TextField(blank=True, db_column='Protein Id', null=True)),
                ('gene_symbol', models.TextField(blank=True, db_column='Gene Symbol', null=True)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
                ('number_of_peptides', models.TextField(blank=True, db_column='Number of peptides', null=True)),
                ('pdx_1', models.TextField(blank=True, db_column='PDX_1', null=True)),
                ('pdx_2', models.TextField(blank=True, db_column='PDX_2', null=True)),
                ('pdx_3', models.TextField(blank=True, db_column='PDX_3', null=True)),
                ('pdxp53_1', models.TextField(blank=True, db_column='PDXp53_1', null=True)),
                ('pdxp53_2', models.TextField(blank=True, db_column='PDXp53_2', null=True)),
                ('pdxp53_3', models.TextField(blank=True, db_column='PDXp53_3', null=True)),
                ('d314', models.TextField(blank=True, db_column='D314', null=True)),
                ('d693', models.TextField(blank=True, db_column='D693', null=True)),
                ('d705', models.TextField(blank=True, db_column='D705', null=True)),
                ('d751', models.TextField(blank=True, db_column='D751', null=True)),
                ('d756', models.TextField(blank=True, db_column='D756', null=True)),
                ('id', models.TextField(blank=True, db_column='Id', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'pancreas_tumor_pro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ScrapedColonPro',
            fields=[
                ('protein_id', models.TextField(blank=True, db_column='Protein Id', null=True)),
                ('gene_symbol', models.TextField(blank=True, db_column='Gene Symbol', null=True)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
                ('group_id', models.TextField(blank=True, db_column='Group ID', null=True)),
                ('number_of_peptides', models.TextField(blank=True, db_column='Number of peptides', null=True)),
                ('collapsed_field', models.TextField(blank=True, db_column='Collapsed?', null=True)),
                ('fabp_1', models.TextField(blank=True, db_column='FABP_1', null=True)),
                ('fabp_2', models.TextField(blank=True, db_column='FABP_2', null=True)),
                ('fabp_4', models.TextField(blank=True, db_column='FABP_4', null=True)),
                ('fabp_5', models.TextField(blank=True, db_column='FABP_5', null=True)),
                ('number_2171_g12d_1', models.TextField(blank=True, db_column='2171_G12D_1', null=True)),
                ('number_2172_g12d_2', models.TextField(blank=True, db_column='2172_G12D_2', null=True)),
                ('g12d_3', models.TextField(blank=True, db_column='G12D_3', null=True)),
                ('g12d_4', models.TextField(blank=True, db_column='G12D_4', null=True)),
                ('average_fabp', models.TextField(blank=True, db_column='Average FABP', null=True)),
                ('average_g12d', models.TextField(blank=True, db_column='Average G12D', null=True)),
                ('average_g12d_average_fabp', models.TextField(blank=True, db_column='Average G12D/Average FABP', null=True)),
                ('id', models.TextField(blank=True, db_column='Id', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'scraped_colon_pro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WholePancreasPro',
            fields=[
                ('protein_id', models.TextField(blank=True, db_column='Protein Id', null=True)),
                ('gene_symbol', models.TextField(blank=True, db_column='Gene Symbol', null=True)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
                ('number_of_peptides', models.TextField(blank=True, db_column='Number of peptides', null=True)),
                ('wt_1', models.TextField(blank=True, null=True)),
                ('wt_2', models.TextField(blank=True, null=True)),
                ('wt_3', models.TextField(blank=True, null=True)),
                ('wt_4', models.TextField(blank=True, null=True)),
                ('g12d_1', models.TextField(blank=True, db_column='G12D_1', null=True)),
                ('g12d_2', models.TextField(blank=True, db_column='G12D_2', null=True)),
                ('g12d_3', models.TextField(blank=True, db_column='G12D_3', null=True)),
                ('id', models.TextField(blank=True, db_column='Id', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'whole_pancreas_pro',
                'managed': False,
            },
        ),
    ]
