# Generated by Django 2.2.6 on 2020-02-02 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0005_auto_20200121_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllProteins',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('protein_id', models.TextField(blank=True, null=True)),
                ('gene_symbol', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'all_proteins',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='AllProPhos',
        ),
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.DeleteModel(
            name='ColonTumorsPhos',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='DjangoPlotlyDashDashapp',
        ),
        migrations.DeleteModel(
            name='DjangoPlotlyDashStatelessapp',
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
        migrations.DeleteModel(
            name='PancreasTumorsPhos',
        ),
        migrations.DeleteModel(
            name='ScrapedColonPhos',
        ),
        migrations.DeleteModel(
            name='SearchProtein',
        ),
        migrations.DeleteModel(
            name='WholePancreasPhos',
        ),
    ]
